### ISSUE TITLE
SEF Compatability

### ISSUE THREAD

**Issue by BTFighter** [furudee/SWAT4-TSS-COOP-AI-Officers#1]
~~While they do spawn on COOP, you can't issue commands to them.~~

Never mind, just didn't press TAB. Can command them now so it's partially compatible.
From what it looks like, the mod just reverts SEF to vanilla TTS SWAT 4

**Comment by furudee** [comment]
SWAT mods that alter the code aren't modular so they're not compatible with other mods out of the box
SEF version coming perhaps one day...

**Comment by BTFighter** [comment]
I see.

Will close this, thanks for the response!
